logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sweater
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    username: maksymkotlyar@gmail.com
    password: pqgvhcesrukcxczh
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail.debug: true
upload.path: d:/programs/javaprojects/sweater/uploads

